dist: xenial
sudo: false
language: python
python:
  - "3.7"
cache: pip
before_install:
  - export TZ=America/New_York
install:
  - pip install --requirement requirements.txt
script:
  - pytest
deploy:
  provider: script
  script: python upkeep.py --workdays-ahead=1 --token=$GH_TOKEN --username=mthielk --repository=elsevier-health/ctha-e-scrum
  skip_cleanup: true
  on:
    branch: master
